version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/.github/autopatcher"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/floorp_downloader"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/patcher_src"
    schedule:
      interval: "daily"
