version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/src/runtime"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/.github/autopatcher"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/src/floorp_downloader"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
