name: Build

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        options:
          - "Artifact"
          - "Release"
      release-notes-url:
        description: Release Notes (ABlog URL)
        type: string
      release-notes-manually:
        description: Manually Release Notes
        type: string

#  schedule:
#    - cron: '0 6 * * *'

jobs:
  build-windows-x86-64:
    runs-on: windows-latest

    steps:
    - name: Prepare git
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache-dependency-path: "**/*.sum"

    - name: Build
      run: |
        curl.exe -L "https://github.com/Floorp-Projects/Floorp/releases/latest/download/floorp-win64.installer.exe" -o floorp-win64.installer.exe
        ./src/utils/7za.exe x floorp-win64.installer.exe -ir!core

        ./build.bat
      env:
        GOARCH: amd64

    - name: Packaging
      run: |
        cd ./dist
        ../src/utils/7za.exe a ../floorp-portable-windows-x86_64.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp-portable-windows-x86_64
        path: |
          ./floorp-portable-windows-x86_64.zip

  build-linux-x86-64:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache-dependency-path: "**/*.sum"

    - name: Build
      run: |
        mkdir core
        cd ./src/floorp_downloader
        npm install
        npm run start linux x86_64
        tar -xvf floorp-package.tar.bz2 -C ../../core --strip-components 1
        cd ../..

        chmod +x ./build.sh
        ./build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "amd64"

    - name: Packaging
      run: |
        cd ./dist
        tar --zstd -cvf ../floorp-portable-linux-x86_64.tar.zst *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp-portable-linux-x86_64
        path: |
          ./floorp-portable-linux-x86_64.tar.zst

  build-linux-aarch64:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install
      run: |
        sudo apt update
        sudo apt install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true
        cache-dependency-path: "**/*.sum"

    - name: Build
      run: |
        mkdir core
        cd ./src/floorp_downloader
        npm install
        npm run start linux aarch64
        tar -xvf floorp-package.tar.bz2 -C ../../core --strip-components 1
        cd ../..

        chmod +x ./build.sh
        ./build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: arm64
        CGO_ENABLED: 1
        CC: aarch64-linux-gnu-gcc
        CXX: aarch64-linux-gnu-g++

    - name: Packaging
      run: |
        cd ./dist
        tar --zstd -cvf ../floorp-portable-linux-aarch64.tar.zst *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp-portable-linux-aarch64
        path: |
          ./floorp-portable-linux-aarch64.tar.zst

  prepare-release:
    runs-on: ubuntu-24.04
    if: github.event.inputs.choice == 'Release'
    needs: [build-windows-x86-64, build-linux-x86-64, build-linux-aarch64]

    steps:
    - uses: actions/download-artifact@v4
      name: Download Linux x86_64 artifact 📥
      with:
        name: floorp-portable-linux-x86_64
        path: linux-x86_64-artifact

    - name: Get version
      run: |
        mkdir ./tmp
        tar -xvf ./linux-x86_64-artifact/floorp-portable-linux-x86_64.tar.zst -C ./tmp

        FLOORP_VERSION=`./tmp/core/floorp -version | awk '{ print $3 }'`

        PORTABLE_VERSION=`cat ./tmp/core/portable_version.txt`

        FLOORP_PORTABLE_VERSION="${FLOORP_VERSION}-${PORTABLE_VERSION}"
        echo "FLOORP_PORTABLE_VERSION=$FLOORP_PORTABLE_VERSION" >> $GITHUB_ENV

        RELEASE_TAG_NAME="${FLOORP_PORTABLE_VERSION}-portable"
        echo "RELEASE_TAG_NAME=$RELEASE_TAG_NAME" >> $GITHUB_ENV

    - name: Display version
      run: |
        echo "Version: ${FLOORP_PORTABLE_VERSION}"

    - name: Check that the version does not already exist
      uses: actions/github-script@v7
      with:
        script: |
          const { data: release } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          if (release.tag_name == process.env.RELEASE_TAG_NAME) {
            throw new Error("The version already exists!");
          }

  release:
    runs-on: ubuntu-24.04
    if: github.event.inputs.choice == 'Release'
    needs: [prepare-release]
    environment: Release

    steps:
    - uses: actions/download-artifact@v4
      name: Download Windows x86_64 artifact 📥
      with:
        name: floorp-portable-windows-x86_64
        path: windows-x86_64-artifact

    - uses: actions/download-artifact@v4
      name: Download Linux x86_64 artifact 📥
      with:
        name: floorp-portable-linux-x86_64
        path: linux-x86_64-artifact

    - uses: actions/download-artifact@v4
      name: Download Linux aarch64 artifact 📥
      with:
        name: floorp-portable-linux-aarch64
        path: linux-aarch64-artifact

    - name: Get version
      run: |
        mkdir ./tmp
        tar -xvf ./linux-x86_64-artifact/floorp-portable-linux-x86_64.tar.zst -C ./tmp

        FLOORP_VERSION=`./tmp/core/floorp -version | awk '{ print $3 }'`

        PORTABLE_VERSION=`cat ./tmp/core/portable_version.txt`

        FLOORP_PORTABLE_VERSION="${FLOORP_VERSION}-${PORTABLE_VERSION}"
        echo "FLOORP_PORTABLE_VERSION=$FLOORP_PORTABLE_VERSION" >> $GITHUB_ENV

    - name: Rename
      run: |
        mv ./windows-x86_64-artifact/floorp-portable-windows-x86_64.zip ./floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-windows-x86_64.zip
        mv ./linux-x86_64-artifact/floorp-portable-linux-x86_64.tar.zst ./floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-x86_64.tar.zst
        mv ./linux-aarch64-artifact/floorp-portable-linux-aarch64.tar.zst ./floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-aarch64.tar.zst

    - name: Generate Release Notes
      if: "${{ github.event.inputs.release-notes-url != '' }}"
      run: |
        git clone https://github.com/Floorp-Projects/ablog2githubrelease
        cd ./ablog2githubrelease
        sudo npm install -g pnpm
        pnpm install
        pnpm run --silent start --url '${{ github.event.inputs.release-notes-url }}' -e 'h2[data-ablog2ghr-innertext*="Download"]' -e ".wp-block-embed" > release-notes.txt

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "${{ env.FLOORP_PORTABLE_VERSION }}-portable"
        target_commitish: ${{ github.sha }}
        make_latest: true
        name: ${{ env.FLOORP_PORTABLE_VERSION }}
        body: ${{ github.event.inputs.release-notes-manually }}
        body_path: "./ablog2githubrelease/release-notes.txt"
        files: |
          floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-windows-x86_64.zip
          floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-x86_64.tar.zst
          floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-aarch64.tar.zst
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update latest.json
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: "Floorp-Updates",
            workflow_id: "update-latest-json-portable.yml",
            ref: "main",
            inputs: {
              "display-version": process.env.FLOORP_PORTABLE_VERSION,
            },
          });
