name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: Floorp-Projects/Floorp-AutoPatcher
        path: tools
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19.4'
    - name: Build
      run: |
        echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"
        go build -ldflags="-H windowsgui" floorp.go
        go build patcher.go
        cd tools
        go build
        copy autopatcher.exe ..
        cd ..
        ./autopatcher.exe -t ${{ secrets.GITHUB_TOKEN }}
        dir
        cd core
        $fver=./floorp.exe  '-version' | more
        echo "fver=$($fver.Split()[2])" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      with:
        name: floorp-${{ env.fver }}-portable
        path: |
            core/
            floorp.exe

