name: Build

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        options:
          - "Artifact"
          - "Release"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Prepare git
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true

    - name: Build
      run: |
        .\build.bat

        # cd .github/autopatcher
        # go build
        # copy autopatcher.exe ../..
        # cd ../..
        # ./autopatcher.exe

        cd floorp_downloader
        npm install
        node floorp_downloader_nightly.mjs windows x86_64
        mkdir tmp
        Expand-Archive -Path ./floorp-package.zip -DestinationPath ./tmp
        cd tmp
        $items = Get-ChildItem ./*.zip -File
        Expand-Archive -Path $items[0] -DestinationPath .
        cd ../..
        Copy-Item -Recurse ./floorp_downloader/tmp/floorp ./core

        ./patcher

        dir
        cd core
        $fver=./floorp.exe  '-version' | more
        echo "fver=$($fver.Split()[2])" >> $env:GITHUB_ENV
        cd ..
      env:
        PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Artifact
      uses: actions/upload-artifact@v3
      if: github.event.inputs.choice == 'Artifact'
      with:
        name: floorp-${{ env.fver }}-portable
        path: |
            core/
            floorp.exe

    - name: Release
      uses: thedoctor0/zip-release@main
      if: github.event.inputs.choice == 'Release'
      with:
        type: 'zip'
        filename: 'floorp-${{ env.fver }}-portable.zip'
        path: |
          core/
          floorp.exe

    - uses: marvinpinto/action-automatic-releases@latest
      if: github.event.inputs.choice == 'Release'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.fver }}-portable"
        title: ${{ env.fver }}
        prerelease: false
        files: |
          floorp-${{ env.fver }}-portable.zip
