name: Build

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        options:
          - "Artifact"
          - "Release"
#  schedule:
#    - cron: '0 6 * * *'

jobs:
  build-windows-x86-64:
    runs-on: windows-latest

    steps:
    - name: Prepare git
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
        cache-dependency-path: ./src/runtime

    - name: Build
      run: |
        curl.exe -L "https://github.com/Floorp-Projects/Floorp/releases/latest/download/floorp-win64.installer.exe" -o floorp-win64.installer.exe
        ./src/utils/7za.exe x floorp-win64.installer.exe -ir!core

        ./build.bat

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp-portable-windows-x86_64
        path: |
          ./dist

  build-linux-x86-64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
        cache-dependency-path: ./src/runtime

    - name: Install
      run: |
        sudo apt update
        sudo apt install -y meson libcap-dev

    - name: Build
      run: |
        mkdir core
        cd ./src/floorp_downloader
        npm install
        npm run start linux x86_64
        tar -xvf floorp-package.tar.bz2 -C ../../core --strip-components 1
        cd ../..

        chmod +x ./build.sh
        ./build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp-portable-linux-x86_64
        path: |
          ./dist

  build-linux-aarch64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
        cache-dependency-path: ./src/runtime

    - name: Install
      run: |
        sudo apt update
        sudo apt install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu meson libcap-dev

    - name: Install aarch64 packages
      uses: ryankurte/action-apt@v0.4.1
      with:
        arch: arm64
        packages: "libcap-dev:arm64"

    - name: Build
      run: |
        mkdir core
        cd ./src/floorp_downloader
        npm install
        npm run start linux aarch64
        tar -xvf floorp-package.tar.bz2 -C ../../core --strip-components 1
        cd ../..

        chmod +x ./build.sh
        ./build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: arm64

    - name: Cross compile Bubblewrap
      run: |
        cd ./src/bubblewrap
        cat <<EOF > ./aarch64-linux-gnu.txt
        [binaries]
        c = 'aarch64-linux-gnu-gcc'
        cpp = 'aarch64-linux-gnu-g++'
        ar = 'aarch64-linux-gnu-ar'
        strip = 'aarch64-linux-gnu-strip'
        pkgconfig = 'pkg-config'

        [host_machine]
        system = 'linux'
        cpu_family = 'aarch64'
        cpu = 'aarch64'
        endian = 'little'

        [build_machine]
        system = 'linux'
        cpu_family = 'x86_64'
        cpu = 'x86_64'
        endian = 'little'
        EOF
        meson setup --cross-file ./aarch64-linux-gnu.txt _builddircross
        meson compile -C _builddircross
        cp ./_builddircross/bwrap ../../dist/bwrap
      env:
        PKG_CONFIG_PATH: "/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
        PKG_CONFIG_LIBDIR: "/usr/lib/aarch64-linux-gnu"
        PKG_CONFIG_SYSROOT_DIR: "/"

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: floorp-portable-linux-aarch64
        path: |
          ./dist

  release:
    runs-on: ubuntu-22.04
    if: github.event.inputs.choice == 'Release'
    needs: [build-windows-x86-64, build-linux-x86-64, build-linux-aarch64]
    environment: Release

    steps:
    - uses: actions/download-artifact@v4
      name: Download Windows x86_64 artifact 📥
      with:
        name: floorp-portable-windows-x86_64
        path: windows-x86_64-artifact

    - uses: actions/download-artifact@v4
      name: Download Linux x86_64 artifact 📥
      with:
        name: floorp-portable-linux-x86_64
        path: linux-x86_64-artifact

    - uses: actions/download-artifact@v4
      name: Download Linux aarch64 artifact 📥
      with:
        name: floorp-portable-linux-aarch64
        path: linux-aarch64-artifact

    - name: Get version
      run: |
        sudo chmod +x ./linux-x86_64-artifact/core/floorp
        FLOORP_VERSION=`./linux-x86_64-artifact/core/floorp -version | awk '{ print $3 }'`

        PORTABLE_VERSION=`cat ./linux-x86_64-artifact/core/portable_version.txt`

        FLOORP_PORTABLE_VERSION="${FLOORP_VERSION}-${PORTABLE_VERSION}"
        echo "FLOORP_PORTABLE_VERSION=$FLOORP_PORTABLE_VERSION" >> $GITHUB_ENV

    - name: Packaging
      run: |
        cd ./windows-x86_64-artifact
        zip ../floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-windows-x86_64.zip -r core floorp.exe
        cd ..

        cd ./linux-x86_64-artifact
        tar --zstd -cf ../floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-x86_64.tar.zst core floorp
        cd ..

        cd ./linux-aarch64-artifact
        tar --zstd -cf ../floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-aarch64.tar.zst core floorp
        cd ..

    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.FLOORP_PORTABLE_VERSION }}"
        title: ${{ env.FLOORP_PORTABLE_VERSION }}
        prerelease: false
        files: |
          floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-windows-x86_64.zip
          floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-x86_64.tar.zst
          floorp-${{ env.FLOORP_PORTABLE_VERSION }}-portable-linux-aarch64.tar.zst
