name: Synchronize translations to Crowdin

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths:
      - l10n/**
    paths-ignore:
      - l10n/en-US.json

concurrency:
  group: crowdin-gh-actions
  cancel-in-progress: false

jobs:
  synchronize-translations-to-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Delete old branch
      uses: actions/github-script@v7
      with:
        script: |
          const branchName = "l10n_develop";

          const { data: branches } = await github.rest.repos.listBranches({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const branchExists = branches.some(branch => branch.name === branchName);

          if (branchExists) {
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branchName}`,
            });
          }

    - name: crowdin action
      uses: crowdin/github-action@v2
      with:
        config: "crowdin.yml"
        upload_sources: true
        upload_translations: true
        auto_approve_imported: true
        download_sources: false
        download_translations: false
        create_pull_request: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
